### ISSUE TITLE
[Bug] tailwind not working yarn workspace 

### ISSUE THREAD

**Issue by 05aj** [storybookjs/addon-styling#54]
### Describe the bug

```ts
import path from "path";

import type { StorybookConfig } from "@storybook/react-webpack5";
const config: StorybookConfig = {
  stories: ["../src/**/*.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
  addons: [
    path.dirname(
      require.resolve(path.join("@storybook/addon-links", "package.json"))
    ),
    path.dirname(
      require.resolve(path.join("@storybook/addon-essentials", "package.json"))
    ),
    path.dirname(
      require.resolve(
        path.join("@storybook/addon-interactions", "package.json")
      )
    ),
    {
      name: path.dirname(
        require.resolve(path.join("@storybook/addon-styling", "package.json"))
      ),
      options: {
        postCss: true,
      },
    },
  ],
  framework: {
    name: path.dirname(
      require.resolve(path.join("@storybook/react-webpack5", "package.json"))
    ),
    options: {},
  },
  docs: {
    autodocs: "tag",
  },
};
export default config;
```

this is my `main.ts` This works for simple yarn pnp but When using workspace, the following error occurs.

```
ModuleBuildError: Module build failed: Error: postcss-loader tried to access postcss (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.

Required package: postcss (via "postcss/package.json")
Required by: postcss-loader@virtual:25bdc57a28882b559bd319afa4ad309eeb8921fce852884ad5b617571ee04ab9203431f3c665b52a4b3919b4d720d53e73b4cb1ca67bd2bbc5e3872bc7ab4ef8#npm:7.3.3 (via /Users/josanghyeon/Desktop/react-sb/.yarn/__virtual__/postcss-loader-virtual-790b554389/0/cache/postcss-loader-npm-7.3.3-df90db4d0c-c724044d6a.zip/node_modules/postcss-loader/dist/)

Ancestor breaking the chain: @storybook/addon-styling@virtual:d5bdf4e4ec3b58747224ef475ffbddc0ba83547aeb41b3a1d8f8efd2b598f809954bb8a93d89ef63f1f32194e2ab878128b5f35e7877f43281371c19d46f1025#npm:1.3.0


Require stack:
- /Users/josanghyeon/Desktop/react-sb/.yarn/__virtual__/postcss-loader-virtual-790b554389/0/cache/postcss-loader-npm-7.3.3-df90db4d0c-c724044d6a.zip/node_modules/postcss-loader/dist/index.js
- /Users/josanghyeon/Desktop/react-sb/.yarn/__virtual__/postcss-loader-virtual-790b554389/0/cache/postcss-loader-npm-7.3.3-df90db4d0c-c724044d6a.zip/node_modules/postcss-loader/dist/cjs.js
- /Users/josanghyeon/Desktop/react-sb/.yarn/__virtual__/webpack-virtual-bf267a9da6/0/cache/webpack-npm-5.87.0-205489994f-b7d0e390f9.zip/node_modules/webpack/lib/ProgressPlugin.js
- /Users/josanghyeon/Desktop/react-sb/.yarn/__virtual__/webpack-virtual-bf267a9da6/0/cache/webpack-npm-5.87.0-205489994f-b7d0e390f9.zip/node_modules/webpack/lib/index.js
- /Users/josanghyeon/Desktop/react-sb/.yarn/__virtual__/@storybook-builder-webpack5-virtual-bedea5ef74/0/cache/@storybook-builder-webpack5-npm-7.0.22-d2b761428e-3890254f23.zip/node_modules/@storybook/builder-webpack5/dist/index.js
    at require$$0.Module._resolveFilename (/Users/josanghyeon/Desktop/react-sb/.pnp.cjs:24596:13)
    at require$$0.Module._load (/Users/josanghyeon/Desktop/react-sb/.pnp.cjs:24446:42)
    at Module.require (node:internal/modules/cjs/loader:1127:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.<anonymous> (/Users/josanghyeon/Desktop/react-sb/.yarn/__virtual__/postcss-loader-virtual-790b554389/0/cache/postcss-loader-npm-7.3.3-df90db4d0c-c724044d6a.zip/node_modules/postcss-loader/dist/index.js:8:39)
    at Module._compile (node:internal/modules/cjs/loader:1246:14)
    at Module._compile (/Users/josanghyeon/Desktop/react-sb/.yarn/__virtual__/esbuild-register-virtual-21e593cad7/0/cache/esbuild-register-npm-3.4.2-c873c16acc-f65d1ccb58.zip/node_modules/esbuild-register/dist/node.js:2258:26)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
    at require$$0.Module._extensions..js (/Users/josanghyeon/Desktop/react-sb/.pnp.cjs:24640:33)
    at Object.newLoader (/Users/josanghyeon/Desktop/react-sb/.yarn/__virtual__/esbuild-register-virtual-21e593cad7/0/cache/esbuild-register-npm-3.4.2-c873c16acc-f65d1ccb58.zip/node_modules/esbuild-register/dist/node.js:2262:9)
    at processResult (/Users/josanghyeon/Desktop/react-sb/.yarn/__virtual__/webpack-virtual-bf267a9da6/0/cache/webpack-npm-5.87.0-205489994f-b7d0e390f9.zip/node_modules/webpack/lib/NormalModule.js:764:19)
    at NormalModule._doBuild (/Users/josanghyeon/Desktop/react-sb/.yarn/__virtual__/webpack-virtual-bf267a9da6/0/cache/webpack-npm-5.87.0-205489994f-b7d0e390f9.zip/node_modules/webpack/lib/NormalModule.js:817:4)
    at NormalModule.build (/Users/josanghyeon/Desktop/react-sb/.yarn/__virtual__/webpack-virtual-bf267a9da6/0/cache/webpack-npm-5.87.0-205489994f-b7d0e390f9.zip/node_modules/webpack/lib/NormalModule.js:969:15)
    at <anonymous> (/Users/josanghyeon/Desktop/react-sb/.yarn/__virtual__/webpack-virtual-bf267a9da6/0/cache/webpack-npm-5.87.0-205489994f-b7d0e390f9.zip/node_modules/webpack/lib/Compilation.js:1377:12)
    at NormalModule.needBuild (/Users/josanghyeon/Desktop/react-sb/.yarn/__virtual__/webpack-virtual-bf267a9da6/0/cache/webpack-npm-5.87.0-205489994f-b7d0e390f9.zip/node_modules/webpack/lib/NormalModule.js:1257:32)
    at Compilation._buildModule (/Users/josanghyeon/Desktop/react-sb/.yarn/__virtual__/webpack-virtual-bf267a9da6/0/cache/webpack-npm-5.87.0-205489994f-b7d0e390f9.zip/node_modules/webpack/lib/Compilation.js:1358:10)
    at <anonymous> (/Users/josanghyeon/Desktop/react-sb/.yarn/__virtual__/webpack-virtual-bf267a9da6/0/cache/webpack-npm-5.87.0-205489994f-b7d0e390f9.zip/node_modules/webpack/lib/util/AsyncQueue.js:305:10)
    at Hook.eval [as callAsync] (eval at create (/Users/josanghyeon/Desktop/react-sb/.yarn/cache/tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:6:1)
    at AsyncQueue._startProcessing (/Users/josanghyeon/Desktop/react-sb/.yarn/__virtual__/webpack-virtual-bf267a9da6/0/cache/webpack-npm-5.87.0-205489994f-b7d0e390f9.zip/node_modules/webpack/lib/util/AsyncQueue.js:295:26)
    at AsyncQueue._ensureProcessing (/Users/josanghyeon/Desktop/react-sb/.yarn/__virtual__/webpack-virtual-bf267a9da6/0/cache/webpack-npm-5.87.0-205489994f-b7d0e390f9.zip/node_modules/webpack/lib/util/AsyncQueue.js:282:12)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

How to resolve this problem??

As far as I can see, the error occurs on the following line.
```ts
options: {
    postCss: true,
}
```

**Comment by Integrayshaun** [comment]
Hey @05lazy 👋 

Can you make sure you have postcss 8 in your dependencies then try updating your addon options to the following:

```js
{
      name: path.dirname(
        require.resolve(path.join("@storybook/addon-styling", "package.json"))
      ),
      options: {
        postCss: { implementation: require.resolve(path.join("postcss", "package.json")) }
      },
    },
```

**Comment by 05lazy** [comment]
@Integrayshaun I tried the solution you said, but I get the same error. Anything else to consider?

**Comment by Integrayshaun** [comment]
@05lazy Can you share your package.json for the project, please?

**Comment by 05lazy** [comment]
Thank for comment @Integrayshaun  😚

my root package.json is

```json
{
  "name": "react-sb",
  "packageManager": "yarn@3.5.0",
  "workspaces": {
    "packages": [
      "package/*"
    ]
  },
  "dependencies": {
    "typescript": "5.0.4"
  }
}
```

my `pacakge > pacakge.json` is

```json
{
  "name": "@package/sb",
  "packageManager": "yarn@3.5.0",
  "devDependencies": {
    "@babel/core": "^7.22.5",
    "@babel/preset-env": "^7.22.5",
    "@babel/preset-react": "^7.22.5",
    "@babel/preset-typescript": "^7.22.5",
    "@storybook/addon-essentials": "^7.0.22",
    "@storybook/addon-interactions": "^7.0.22",
    "@storybook/addon-links": "^7.0.22",
    "@storybook/addon-postcss": "^2.0.0",
    "@storybook/addon-styling": "^1.3.0",
    "@storybook/blocks": "^7.0.22",
    "@storybook/react": "^7.0.22",
    "@storybook/react-webpack5": "^7.0.22",
    "@storybook/testing-library": "^0.0.14-next.2",
    "@types/node": "^20.3.1",
    "@types/react": "^18.2.13",
    "@types/react-dom": "^18.2.6",
    "autoprefixer": "^9",
    "postcss": "^8.4.24",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "storybook": "^7.0.22",
    "tailwindcss": "^3.3.2",
    "typescript": "5.0.4"
  },
  "scripts": {
    "storybook": "storybook dev -p 6006",
    "build-storybook": "storybook build"
  }
}
```

**Comment by 05lazy** [comment]
@Integrayshaun 

This is a repo I've simply put together for you. -> https://github.com/05lazy/yarn-workspace-starter

You can do `yarn install` once and run `yarn workspace @cli/react-sb storybook`.

**Comment by Integrayshaun** [comment]
Thank you so much @05lazy 😄 this will help a ton. I’ll boot it up this morning and see what I can do

**Comment by 05aj** [comment]
@Integrayshaun I`m pending...

**Comment by Integrayshaun** [comment]
hi @05aj I'm sorry, I was away on vacation last week and it's only me maintaining this library.

I will try to get to an answer for you as soon as I can. This is a case that i'm less familiar with

**Comment by 05aj** [comment]
[this link](https://storybook.js.org/recipes/tailwindcss) recommanded this library. 

Sorry for rushing you. 😓 But I wanted to quickly try Storybook + tailwind + yarn workspace. Thank you for your understanding.

**Comment by Integrayshaun** [comment]
@05aj okay, I've had some time to did into it and this is due to yarn pnp. Without listing postcss 8 as a peer dependency in addon-styling, your project doesn't have permission to access it. I'll publish an update to the package with this change this week.

There are a few other problems with your setup that will cause you a problem afterwards.

1. Make sure to add `tailwindcss` as a devDep for your storybook template in the repo. It was missing in your example repo for me.
2. Your `postcss.config.js` file needs to be updated to require the postcss plugins you want
```diff
-module.exports = {
-  plugins: {
-    tailwindcss: {},
-    autoprefixer: {},
-  },
- };
+/** @type {import('postcss-load-config').Config} */
+const config = {
+  plugins: [
+    require('tailwindcss'),
+    require('autoprefixer'),
+  ]
+}
+
+module.exports = config
```

**Comment by 05aj** [comment]
@Integrayshaun 
It doesn't seem like it. As I said before, it worked normally in yarn pnp, but it does not work in the workspace environment. As of now, I've tried updating the repository as per your solution, but I get the same error. Could you please check the [repositories](https://github.com/05aj/yarn-workspace-starter) once again?

**Comment by Integrayshaun** [comment]
@05aj i haven’t published the update to the styling addon yet that you need in order to make this work with yarn workspaces and PnP.

I need more time to test it to make sure it doesn’t break the addon for other cases

**Comment by 05aj** [comment]
OK, I'll wait until this addon supports yarn workspace.

**Comment by 05aj** [comment]
@Integrayshaun Oh I've confirmed that it works fine. Thank you for solving it for a long time. 😎😍

**Comment by Integrayshaun** [comment]
You're very welcome, @05aj! Apologies for the long wait
